# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "621672204142-terraform-tfstate"
    dynamodb_table = "mrionline-global-prod-terraform-lock"
    encrypt        = true
    key            = "prod/redis/terraform.tfstate"
    region         = "us-east-2"
  }
}
