#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
#------------------------------------------------------------------------------
name: Print tutor config.yml to the console
branding:
  icon: 'cloud'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Dump tutor config.yml
      shell: bash
      continue-on-error: true
      run: |-
        echo 'config.yml:'
        echo '-------------------------------------'
        cat $(tutor config printroot)/config.yml
