#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Deploys a Tutor-created openedx Docker image to the Kubernetes cluster.
#        The openedx docker image is created by a Github action in tutor-build.git.
#------------------------------------------------------------------------------
name: Deploy Open edX prod to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy prod
        uses: ./.github/workflows/tutor_deploy
        with:
          environment-id: prod
          namespace: openedx-prod
          openedx-common-version: open-release/maple.3
          aws-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-ses-iam-key: ${{ secrets.AWS_SES_IAM_KEY }}
          aws-ses-iam-secret: ${{ secrets.AWS_SES_IAM_SECRET }}
