#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Deploys a Tutor-created openedx Docker image to the Kubernetes cluster.
#        The openedx docker image is created by a Github action in tutor-build.git.
#------------------------------------------------------------------------------
name: Test workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENABLE_S3: true
      ENABLE_BACKUP: true
      ENABLE_DISCOVERY: true
      ENABLE_MFE: true
      ENABLE_CREDENTIALS: true
      ENABLE_XQUEUE: true
      ENABLE_NOTES: true
      ENABLE_ECOMMERCE: true
      ENABLE_FORUM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      # grab the AWS IAM key and scret for the IAM user named 'ci'
      # These are manually stored in https://github.com/Medality-Health/openedx_devops/settings
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Tutor deploy init
        uses: ./.github/workflows/tutor/deploy/tutor-deploy-init
        with:
          environment-id: prod
          namespace: openedx-prod
          openedx-common-version: open-release/maple.3

      - name: test whether installed software works here
        run: |-
          kubectl version --short
          echo
          echo "aws cli version:"
          aws --version

      - name: Enable tutor plugin - S3
        uses: openedx-actions/tutor-enable-plugin-s3
        if: ${{ env.ENABLE_S3 == 'true' }}
        with:
          namespace: openedx-prod

      - name: Enable tutor plugin - Backup
        uses: openedx-actions/tutor-enable-plugin-backup@v0.0.1
        if: ${{ env.ENABLE_BACKUP == 'true' }}
        with:
          aws-ecr-uri: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_backup:latest
          namespace: openedx-prod

      - name: Enable tutor plugin - Discovery
        uses: openedx-actions/tutor-enable-plugin-discovery@v0.0.1
        if: ${{ env.ENABLE_DISCOVERY == 'true' }}
        with:
          namespace: openedx-prod

      - name: Enable tutor plugin - MFE
        uses: openedx-actions/tutor-enable-plugin-mfe@v0.0.1
        if: ${{ env.ENABLE_MFE == 'true' }}
        with:
          aws-ecr-uri: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_mfe:latest

      - name: Enable tutor plugin - Credentials
        uses: openedx-actions/tutor-enable-plugin-credentials@v0.0.1
        if: ${{ env.ENABLE_CREDENTIALS == 'true' }}
        with:
          namespace: openedx-prod
          aws-ecr-uri: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_credentials:latest
          common-logo-url: https://www.edx.org/images/logos/edx-logo-elm.svg

      - name: Enable tutor plugin - Xqueue
        uses: openedx-actions/tutor-enable-plugin-xqueue@v0.0.1
        if: ${{ env.ENABLE_XQUEUE == 'true' }}
        with:
          namespace: openedx-prod

      - name: Enable tutor plugin - Notes
        uses: openedx-actions/tutor-enable-plugin-notes@v0.0.1
        if: ${{ env.ENABLE_NOTES == 'true' }}
        with:
          namespace: openedx-prod

      - name: Enable tutor plugin - Ecommerce
        uses: openedx-actions/tutor-enable-plugin-ecommerce@v0.0.1
        if: ${{ env.ENABLE_ECOMMERCE == 'true' }}
        with:
          namespace: openedx-prod

      - name: Enable tutor plugin - Forum
        uses: openedx-actions/tutor-enable-plugin-forum@v0.0.1
        if: ${{ env.ENABLE_FORUM == 'true' }}

      - name: test whether we can dump the tutor config to the console
        run: |-
          echo $(tutor config printroot)/config.yml
          cat $(tutor config printroot)/config.yml
