#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Deploys a Tutor-created openedx Docker image to the Kubernetes cluster.
#        The openedx docker image is created by a Github action in tutor-build.git.
#------------------------------------------------------------------------------
name: Test workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      # grab the AWS IAM key and scret for the IAM user named 'ci'
      # These are manually stored in https://github.com/Medality-Health/openedx_devops/settings
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Test enable plugins
        uses: ./.github/workflows/tutor/deploy/plugins/tutor-enable-plugins
        with:
          tutor-enable-plugin-s3: true
          tutor-enable-plugin-backup: false
          tutor-enable-plugin-discovery: false
          tutor-enable-plugin-mfe: false
          tutor-enable-plugin-credentials: false
          tutor-enable-plugin-xqueue: false
          tutor-enable-plugin-notes: false
          tutor-enable-plugin-ecommerce: false
          tutor-enable-plugin-forum: false

      - name: Test init
        uses: ./.github/workflows/tutor/deploy/tutor-deploy-init
        with:
          environment-id: prod
          namespace: openedx-prod
          openedx-common-version: open-release/maple.3

      - name: test whether installed software works here
        run: |-
          kubectl version --short
          echo
          echo "aws cli version:"
          aws --version


      - name: test whether we can dump the tutor config to the console
        run: |-
          echo $(tutor config printroot)/config.yml
          cat $(tutor config printroot)/config.yml
