#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Deploys a Tutor-created openedx Docker image to the Kubernetes cluster.
#        The openedx docker image is created by a Github action in tutor-build.git.
#------------------------------------------------------------------------------
name: Test workflows

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # common settings
      # --------------------------------------------
      AWS_ACCOUNT_NUMBER: '123456789012'
      AWS_ECR_HOST: 'dkr.ecr.us-east-2.amazonaws.com'

      # environment settings
      # --------------------------------------------
      ENVIRONMENT_ID: prod
      NAMESPACE: openedx-prod

      # feature flags for optional tutor modules
      # --------------------------------------------
      ENABLE_S3: true
      ENABLE_BACKUP: true
      ENABLE_DISCOVERY: true
      ENABLE_MFE: true
      ENABLE_CREDENTIALS: true
      ENABLE_XQUEUE: true
      ENABLE_NOTES: true
      ENABLE_ECOMMERCE: true
      ENABLE_FORUM: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      # ---------------------------------------------------------------------------------
      # initialize workflow environment variables
      # ---------------------------------------------------------------------------------
      - name: Intialize AWS_ECR_URI
        shell: bash
        run: |-
          echo "AWS_ECR_URI=${{ env.AWS_ACCOUNT_NUMBER }}.${{ env.AWS_ECR_HOST }}" >> $GITHUB_ENV

      - name: Intialize AWS ECR repo URIs
        shell: bash
        run: |-
          echo "AWS_ECR_REPOSITORY_BACKUP=${AWS_ECR_URI}/openedx_backup:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_CREDENTIALS=${AWS_ECR_URI}/openedx_credentials:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_MFE=${AWS_ECR_URI}/openedx_mfe:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_OPENEDX=${AWS_ECR_URI}/openedx:latest" >> $GITHUB_ENV

      # ---------------------------------------------------------------------------------
      # initialize this Github workspace environment: python, tutor, kubectl, aws cli
      # ---------------------------------------------------------------------------------
      - name: Initialize environment
        uses: ./.github/workflows/tutor/k8s/init
        with:
          environment-id: prod
          namespace: openedx-prod
          openedx-common-version: open-release/maple.3
          aws-ecr-uri: ${AWS_ECR_REPOSITORY_OPENEDX}
