#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: Creates a Tutor Docker image using the latest stable version of Open edX.
#        additionally installs
#        - custom theme
#        - plugin
#        - various Xblocks
#        Registers the new container in AWS ECR.
#------------------------------------------------------------------------------
name: Build openedx Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: openedx
      ECR_REGISTRY: 621672204142.dkr.ecr.us-east-2.amazonaws.com
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build the image and upload to AWS ECR
        uses: openedx-actions/tutor-plugin-build-openedx@v0.1.6
        with:
          custom-theme-repository: 'lpm0073/edx-theme-example'
          custom-theme-repository-ref: 'main'

          custom-plugin-repository: 'openedx-plugin-example'
          custom-plugin-repository-organization: 'lpm0073'
          custom-plugin-repository-ref: 'main'

          custom-xblock-repository: 'edx-ora2'
          custom-xblock-repository-organization: 'openedx'
          custom-xblock-repository-ref: 'master'
