#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: enable Discussion Forum for deployment to Kubernetes cluster
#
#------------------------------------------------------------------------------
name: enable MFE plugin for tutor

on: [workflow_call]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_MFE: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_mfe:latest

    steps:
      - name: Enable the MFE plugin
        run: |-
          pip install tutor-mfe
          tutor plugins enable mfe
          tutor config save --set MFE_DOCKER_IMAGE=${DOCKER_IMAGE_MFE} \
                            --set MFE_ENABLE_HTTPS=true
