#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: deploy a Tutor-created openedx Docker image to the Kubernetes cluster.
#        The openedx docker image is created by a Github action in tutor-build.git.
#
#        The general work flow in this action is:
#        ----------------------------------------
#        I.   Bootstrap the Github Actions Ubuntu instance.
#        II.  Get backend services configuration data stored in Kubernetes secrets
#        III. Configure Open edX by setting environment variables
#        IV.  Merge all of the configuration data into Tutor's Open edX configuration files
#        V.   Deploy Open edX into the Kubernetes cluster
#------------------------------------------------------------------------------
name: enable Backup plugin for tutor

on: [workflow_call]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_BACKUP: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_backup:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      # IMPORTANT: you must run tutor_build_hastexo_backup first.
      #
      # See the github README for additional AWS S3 configuration
      # options in the event that you are not also installing
      # hastexo/tutor-contrib-s3 (included above)
      - name: Enable the hastexo Backup & Restore plugin
        run: |-
          pip install git+https://github.com/hastexo/tutor-contrib-backup@v0.0.6
          tutor plugins enable backup

          tutor config save --set BACKUP_DOCKER_IMAGE=${DOCKER_IMAGE_BACKUP} \
                            --set BACKUP_K8S_CRONJOB_HISTORYLIMIT_FAILURE=1 \
                            --set BACKUP_K8S_CRONJOB_HISTORYLIMIT_SUCCESS=3 \
                            --set BACKUP_K8S_CRONJOB_BACKUP_SCHEDULE="0 0 * * *" \
                            --set BACKUP_S3_BUCKET_NAME="$S3_BACKUP_BUCKET"
