#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: conigure tutor SMTP email service
#        Called from tutor_deploy.yml
#
# FIX NOTE: move to Github Actions marketplace
#------------------------------------------------------------------------------
name: enable Xqueue plugin for tutor

on:
  workflow_call:
  secrets:
    aws-ses-iam-key:
      description: 'AWS IAM key for AWS SES email service'
      required: true
    aws-ses-iam-secret:
      description: 'AWS IAM secret for AWS SES email service'
      required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------------------------
      # Note: We're not managing AWS SES with Terraform simply because the service is fiddly
      # and AWS is neurotic about any changes to the config.
      # ---------------------------------------------------------------------------------
      - name: Setup AWS SES over SMTP
        run: |-
          echo "TUTOR_RUN_SMTP=true" >> $GITHUB_ENV
          tutor config save --set EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend" \
                            --set EMAIL_HOST="email-smtp.us-east-2.amazonaws.com" \
                            --set EMAIL_HOST_PASSWORD=${{ secrets.aws-ses-iam-key }} \
                            --set EMAIL_HOST_USER=${{ secrets.aws-ses-iam-secret }} \
                            --set EMAIL_PORT=587 \
                            --set EMAIL_USE_TLS=true
