#------------------------------------------------------------------------------
# written by: mcdaniel
# date: feb-2022
#
# usage: enable Discussion Forum for deployment to Kubernetes cluster
#
#------------------------------------------------------------------------------
name: enable Notes plugin for tutor

on: [workflow_call]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      # retrieve the MySQL connection parameters that we created in Terraform
      # and then stored in Kubernetes secrets. These include:
      #   MYSQL_HOST: mysql.app.mrionline.com
      #   MYSQL_PORT: "3306"
      #   OPENEDX_MYSQL_USERNAME: openedx
      #   OPENEDX_MYSQL_PASSWORD: **************
      #   MYSQL_ROOT_USERNAME: root
      #   MYSQL_ROOT_PASSWORD: *************
      #
      # Also note that we are using jq to add a prefix of "TUTOR_" to each of the parameter names
      #
      # see: https://github.com/Medality-Health/openedx_devops/blob/main/terraform/modules/mysql/main.tf
      - name: fetch MySQL configuration from Kubernetes secrets
        run: |-
          kubectl get secret mysql-notes -n $NAMESPACE  -o json | jq  '.data | map_values(@base64d)' | jq -r 'keys[] as $k | "TUTOR_\($k|ascii_upcase)=\(.[$k])"' >> $GITHUB_ENV

      - name: Enable the Notes plugin
        run: |-
          pip install tutor-notes
          tutor plugins enable notes
          tutor config save
