#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com/
#
# date: May-2022
#
# usage: Creates a Tutor Docker image for MFE using the latest stable version of
#        the repo. Registers the new container in AWS ECR.
#------------------------------------------------------------------------------
name: Build Micro Front-end (MFE) Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: openedx_mfe
      ECR_REGISTRY: 621672204142.dkr.ecr.us-east-2.amazonaws.com

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build the image and upload to AWS ECR
        uses: openedx-actions/tutor-plugin-build-mfe
        with:
          subdomain: 'app'
          domain-name: 'mrionline.com'
          site-name: 'Your School'
